name: Validate with hassfest
env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - name: Check out repository
        uses: "actions/checkout@v4"

      - name: Run hassfest
        uses: "home-assistant/actions/hassfest@master"

      - name: HACS Action
        uses: "hacs/action@22.5.0"
        with:
          category: "integration"
